---
# tasks file for install_nginx
- name: Install nginx for server
  package:
    name: nginx
    state: latest
    update_cache: yes

- name: Start nginx for servers
  service:
    name: nginx
    state: started

- name: Copy main config file for nginx - nginx.conf
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0744
  notify: restart nginx
    
- name: Copy config file for nginx - http.conf
  template:
    src: ../templates/http.conf.j2
    dest: /etc/nginx/conf.d/http.conf
    mode: 0744
  notify: restart nginx

- name: Create ssl dir
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Copy cert and key on hosts
  copy:
    src: "../files/{{ item }}"
    dest: "{{ ssl_dir }}"
    with_items:
      - example.crt
      - example.key

- name: restart nginx
  meta: flush_handlers