pipeline {
    agent any

    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['test_server', 'prod_server'],
            description: 'Выберите окружение для деплоя'
        )
        string(
            name: 'TARGET_HOSTS',
            defaultValue: 'all',
            description: 'Целевые хосты или группа из inventory'
        )
        booleanParam(
            name: 'RECONFIG_MODE',
            defaultValue: false,
            description: 'Только проверка конфигурации без запуска на хостах'
        )
    }

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'false'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/AlexOBel/ansible_training.git',
                    credentialsId: 'https_github_cred'
            }
        }

        stage('Inventory Check') {
            steps {
                sh """
                    ansible-inventory -i ./playbook_nginx/inventory/${params.ENVIRONMENT}.yml --list
                    ansible-inventory -i ./playbook_nginx/inventory/${params.ENVIRONMENT}.yml --graph
                """
            }
            when {
                expression { params.RECONFIG_MODE == true }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                script {
                    withCredentials([
                        sshUserPrivateKey(
                            credentialsId: 'AnsibleUser',
                            keyFileVariable: 'SSH_KEY_FILE'
                        )
                    ]) {
                        sh """
                            export ANSIBLE_PRIVATE_KEY_FILE=${SSH_KEY_FILE}
                            ansible-playbook \
                                -i inventory/${params.ENVIRONMENT}.yml \
                                -l ${params.TARGET_HOSTS} \
                                --extra-vars "env=${params.ENVIRONMENT}" \
                                ${params.RECONFIG_MODE ? '--check --diff' : ''} \
                                ./playbook_nginx/playbook.yml
                        """
                    }
                }
            }
            when {
               expression { params.RECONFIG_MODE == false }
            }
        }
    }
}