---

- name: update system
  hosts: all
  shell: 'yum update -y'
  become: true

- name: install NGINX
  hosts: all
  become: true
  roles:
    - install_and_deploy_nginx

  vars:
    ssl_dir: /etc/nginx/ssl

  tasks:
    - name: msg for success deploy
      debug:
        msg: Nginx success deploy and configure