---

- name: install NGINX
  become: true
  include_role:
    name: install_and_deploy_nginx

  vars:
    ssl_dir: /etc/nginx/ssl

  tasks:
    - name: msg for success deploy
      msg: Nginx success deploy and configure