all:
   children:
      loadbalancers:
         hosts:
            lb_1:
               ansible_host: 192.168.3.55
               status: master
            lb_2:
               ansible_host: 192.168.3.56
               status: slave